### ISSUE TITLE
handle using AWS Secrets from Secret vault

### ISSUE THREAD

**Issue by llimon** [llimon/argoscheduler-controller#1]
Currently, AWS Secrets have to be specified as part of the Yaml. Anyone with namespace access read will be able to see them.

We need to support Kubernetes secrets (and KIM roles).

I'm thinking something like this:
```
  Spec:
    Filewatcher:
      AccessKey:
        valueFrom:
	  secretKeyRef:
	    name: mysecret
	    key: username
```
